<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Frog.DemoWorld</RootNamespace>
    <AssemblyName>Frog.DemoWorld</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Frog.Persistence.PostgreSql\Frog.Persistence.PostgreSql.csproj" />
    <ProjectReference Include="..\..\Frog.Application\Frog.Application.csproj" />
  </ItemGroup>
</Project>
