// <auto-generated />
using System;
using Frog.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frog.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(FrogDbContext))]
    [Migration("20260822040506_InitialMapPersistence")]
    partial class InitialMapPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("world")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.LegacyImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("format_type");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("report_json");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256hex");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path");

                    b.HasKey("Id")
                        .HasName("pk_legacy_imports");

                    b.HasIndex("Sha256Hex", "FormatType")
                        .IsUnique()
                        .HasDatabaseName("ix_legacy_imports_sha256hex_format_type");

                    b.ToTable("legacy_imports", "ops");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapCellEntity", b =>
                {
                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("LayersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_json");

                    b.HasKey("MapId", "X", "Y")
                        .HasName("pk_map_cells");

                    b.ToTable("map_cells", "world", t =>
                        {
                            t.HasCheckConstraint("ck_map_cells_in_bounds", "x >= 0 AND y >= 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPlayerOverlap")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_player_overlap");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LayersCatalogJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_catalog_json");

                    b.Property<int>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_maps");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_maps_legacy_id");

                    b.ToTable("maps", "world", t =>
                        {
                            t.HasCheckConstraint("ck_maps_non_negative_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_maps_positive_size", "width > 0 AND height > 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapNpcSpawnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("NpcDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_definition_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_map_npc_spawns");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_map_npc_spawns_map_id");

                    b.ToTable("map_npc_spawns", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapWarpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DestinationUnresolved")
                        .HasColumnType("boolean")
                        .HasColumnName("destination_unresolved");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("SourceX")
                        .HasColumnType("integer")
                        .HasColumnName("source_x");

                    b.Property<int>("SourceY")
                        .HasColumnType("integer")
                        .HasColumnName("source_y");

                    b.Property<int>("TargetLegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("target_legacy_id");

                    b.Property<int>("TargetX")
                        .HasColumnType("integer")
                        .HasColumnName("target_x");

                    b.Property<int>("TargetY")
                        .HasColumnType("integer")
                        .HasColumnName("target_y");

                    b.HasKey("Id")
                        .HasName("pk_map_warps");

                    b.HasIndex("MapId", "SourceX", "SourceY")
                        .IsUnique()
                        .HasDatabaseName("ix_map_warps_map_id_source_x_source_y");

                    b.ToTable("map_warps", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logical_path");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256hex");

                    b.Property<int>("TileSizePixels")
                        .HasColumnType("integer")
                        .HasColumnName("tile_size_pixels");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_tilesets");

                    b.HasIndex("LogicalPath")
                        .IsUnique()
                        .HasDatabaseName("ix_tilesets_logical_path");

                    b.ToTable("tilesets", "content");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapCellEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("Cells")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_cells_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapNpcSpawnEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("NpcSpawns")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_npc_spawns_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapWarpEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("Warps")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_warps_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapEntity", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("NpcSpawns");

                    b.Navigation("Warps");
                });
#pragma warning restore 612, 618
        }
    }
}
