// <auto-generated />
using System;
using Frog.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frog.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(FrogDbContext))]
    [Migration("20260823224117_NpcDraftPublish")]
    partial class NpcDraftPublish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("world")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.LegacyImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("format_type");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("report_json");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256hex");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path");

                    b.HasKey("Id")
                        .HasName("pk_legacy_imports");

                    b.HasIndex("Sha256Hex", "FormatType")
                        .IsUnique()
                        .HasDatabaseName("ix_legacy_imports_sha256hex_format_type");

                    b.ToTable("legacy_imports", "ops");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapCellEntity", b =>
                {
                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("LayersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_json");

                    b.HasKey("MapId", "X", "Y")
                        .HasName("pk_map_cells");

                    b.ToTable("map_cells", "world", t =>
                        {
                            t.HasCheckConstraint("ck_map_cells_in_bounds", "x >= 0 AND y >= 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPlayerOverlap")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_player_overlap");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LayersCatalogJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_catalog_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("PublishedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("published_revision");

                    b.Property<Guid?>("PublishedSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_snapshot_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_maps");

                    b.ToTable("maps", "world", t =>
                        {
                            t.HasCheckConstraint("ck_maps_non_negative_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_maps_positive_size", "width > 0 AND height > 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapNpcSpawnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("NpcDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_definition_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_map_npc_spawns");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_map_npc_spawns_map_id");

                    b.ToTable("map_npc_spawns", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublicationHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_map_publication_history");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_map_publication_history_map_id");

                    b.ToTable("map_publication_history", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedCellEntity", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("LayersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_json");

                    b.HasKey("SnapshotId", "X", "Y")
                        .HasName("pk_map_published_cells");

                    b.ToTable("map_published_cells", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPlayerOverlap")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_player_overlap");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LayersCatalogJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layers_catalog_json");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_map_published_snapshots");

                    b.HasIndex("MapId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_map_published_snapshots_map_id_revision");

                    b.ToTable("map_published_snapshots", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedWarpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DestinationUnresolved")
                        .HasColumnType("boolean")
                        .HasColumnName("destination_unresolved");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("SourceX")
                        .HasColumnType("integer")
                        .HasColumnName("source_x");

                    b.Property<int>("SourceY")
                        .HasColumnType("integer")
                        .HasColumnName("source_y");

                    b.Property<Guid?>("TargetMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_map_id");

                    b.Property<int>("TargetX")
                        .HasColumnType("integer")
                        .HasColumnName("target_x");

                    b.Property<int>("TargetY")
                        .HasColumnType("integer")
                        .HasColumnName("target_y");

                    b.HasKey("Id")
                        .HasName("pk_map_published_warps");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("ix_map_published_warps_snapshot_id");

                    b.ToTable("map_published_warps", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapWarpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DestinationUnresolved")
                        .HasColumnType("boolean")
                        .HasColumnName("destination_unresolved");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<int>("SourceX")
                        .HasColumnType("integer")
                        .HasColumnName("source_x");

                    b.Property<int>("SourceY")
                        .HasColumnType("integer")
                        .HasColumnName("source_y");

                    b.Property<Guid?>("TargetMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_map_id");

                    b.Property<int>("TargetX")
                        .HasColumnType("integer")
                        .HasColumnName("target_x");

                    b.Property<int>("TargetY")
                        .HasColumnType("integer")
                        .HasColumnName("target_y");

                    b.HasKey("Id")
                        .HasName("pk_map_warps");

                    b.HasIndex("TargetMapId")
                        .HasDatabaseName("ix_map_warps_target_map_id");

                    b.HasIndex("MapId", "SourceX", "SourceY")
                        .IsUnique()
                        .HasDatabaseName("ix_map_warps_map_id_source_x_source_y");

                    b.ToTable("map_warps", "world");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.NpcEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("EditorAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("editor_alias_id");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<long?>("PublishedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("published_revision");

                    b.Property<Guid?>("PublishedSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_snapshot_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SpriteLogicalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sprite_logical_path");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_npcs");

                    b.HasIndex("EditorAliasId")
                        .IsUnique()
                        .HasDatabaseName("ix_npcs_editor_alias_id")
                        .HasFilter("editor_alias_id IS NOT NULL");

                    b.ToTable("npcs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npcs_level", "level >= 1 AND level <= 99");

                            t.HasCheckConstraint("ck_npcs_non_negative_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.NpcPublicationHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uuid")
                        .HasColumnName("npc_id");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_npc_publication_history");

                    b.HasIndex("NpcId")
                        .HasDatabaseName("ix_npc_publication_history_npc_id");

                    b.ToTable("npc_publication_history", "content");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.NpcPublishedSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("EditorAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("editor_alias_id");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uuid")
                        .HasColumnName("npc_id");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SpriteLogicalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sprite_logical_path");

                    b.HasKey("Id")
                        .HasName("pk_npc_published_snapshots");

                    b.HasIndex("NpcId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_published_snapshots_npc_id_revision");

                    b.ToTable("npc_published_snapshots", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npc_published_snapshots_level", "level >= 1 AND level <= 99");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("EditorPaletteId")
                        .HasColumnType("integer")
                        .HasColumnName("editor_palette_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logical_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long?>("PublishedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("published_revision");

                    b.Property<Guid?>("PublishedSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_snapshot_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256hex");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("TileSizePixels")
                        .HasColumnType("integer")
                        .HasColumnName("tile_size_pixels");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_tilesets");

                    b.HasIndex("EditorPaletteId")
                        .IsUnique()
                        .HasDatabaseName("ix_tilesets_editor_palette_id")
                        .HasFilter("editor_palette_id IS NOT NULL");

                    b.HasIndex("LogicalPath")
                        .IsUnique()
                        .HasDatabaseName("ix_tilesets_logical_path");

                    b.ToTable("tilesets", "content", t =>
                        {
                            t.HasCheckConstraint("ck_tilesets_non_negative_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_tilesets_positive_size", "width > 0 AND height > 0 AND tile_size_pixels > 0");
                        });
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetPublicationHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("TilesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tileset_id");

                    b.HasKey("Id")
                        .HasName("pk_tileset_publication_history");

                    b.HasIndex("TilesetId")
                        .HasDatabaseName("ix_tileset_publication_history_tileset_id");

                    b.ToTable("tileset_publication_history", "content");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetPublishedSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("EditorPaletteId")
                        .HasColumnType("integer")
                        .HasColumnName("editor_palette_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LogicalPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logical_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256hex");

                    b.Property<int>("TileSizePixels")
                        .HasColumnType("integer")
                        .HasColumnName("tile_size_pixels");

                    b.Property<Guid>("TilesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("tileset_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_tileset_published_snapshots");

                    b.HasIndex("TilesetId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_tileset_published_snapshots_tileset_id_revision");

                    b.ToTable("tileset_published_snapshots", "content");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapCellEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("Cells")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_cells_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapNpcSpawnEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("NpcSpawns")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_npc_spawns_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublicationHistoryEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_publication_history_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedCellEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapPublishedSnapshotEntity", "Snapshot")
                        .WithMany("Cells")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_published_cells_map_published_snapshots_snapshot_id");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedSnapshotEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_published_snapshots_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedWarpEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapPublishedSnapshotEntity", "Snapshot")
                        .WithMany("Warps")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_published_warps_map_published_snapshots_snapshot_id");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapWarpEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "Map")
                        .WithMany("Warps")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_warps_maps_map_id");

                    b.HasOne("Frog.Persistence.PostgreSql.Entities.MapEntity", "TargetMap")
                        .WithMany()
                        .HasForeignKey("TargetMapId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_map_warps_maps_target_map_id");

                    b.Navigation("Map");

                    b.Navigation("TargetMap");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.NpcPublicationHistoryEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.NpcEntity", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_npc_publication_history_npcs_npc_id");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.NpcPublishedSnapshotEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.NpcEntity", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_npc_published_snapshots_npcs_npc_id");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetPublicationHistoryEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.TilesetEntity", "Tileset")
                        .WithMany()
                        .HasForeignKey("TilesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tileset_publication_history_tilesets_tileset_id");

                    b.Navigation("Tileset");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.TilesetPublishedSnapshotEntity", b =>
                {
                    b.HasOne("Frog.Persistence.PostgreSql.Entities.TilesetEntity", "Tileset")
                        .WithMany()
                        .HasForeignKey("TilesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tileset_published_snapshots_tilesets_tileset_id");

                    b.Navigation("Tileset");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapEntity", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("NpcSpawns");

                    b.Navigation("Warps");
                });

            modelBuilder.Entity("Frog.Persistence.PostgreSql.Entities.MapPublishedSnapshotEntity", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Warps");
                });
#pragma warning restore 612, 618
        }
    }
}
