name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./Frog.Creator.sln

      - name: Build
        run: dotnet build ./Frog.Creator.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Frog.Tests/Frog.Tests.csproj --configuration Release --no-build --verbosity normal
